project_id = "lzjhnujekcqljshsqeyi"

[functions.check-follow-ups]
verify_jwt = false

[functions.create-user]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.update-user]
verify_jwt = true